name: API report (rizzkey.js)

on:
  push:
    paths:
      - packages/rizzkey-js/**
  pull_request:
    paths:
      - packages/rizzkey-js/**

jobs:
  report:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version-file: '.node-version'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Build
        run: pnpm --filter rizzkey-js build

      - name: Check files
        run: ls packages/rizzkey-js/built

      - name: API report
        run: pnpm --filter rizzkey-js api-prod

      - name: Show report
        if: always()
        run: cat packages/rizzkey-js/temp/rizzkey-js.api.md
